/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muebleria;

import javax.swing.Box;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Josue
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(755, 483));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menú Admin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(293, 84, 143, 30);

        btnCreate.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnCreate.setText("C");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        getContentPane().add(btnCreate);
        btnCreate.setBounds(86, 306, 120, 80);

        btnRead.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnRead.setText("R");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });
        getContentPane().add(btnRead);
        btnRead.setBounds(235, 306, 120, 80);

        btnUpdate.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnUpdate.setText("U");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(387, 306, 120, 80);

        btnDelete.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        btnDelete.setText("D");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(545, 306, 120, 80);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Productos:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 260, 69, 18);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin-fondo.jpg"))); // NOI18N
        fondo.setText("jLabel3");
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 750, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        JTextField txtMaterial = new JTextField(5);
        JTextField txtTipoP = new JTextField(5);
        JTextField txtDimensiones = new JTextField(5);
        JTextField txtPrecio = new JTextField(5);
        JTextField txtNombre = new JTextField(5);
        JTextField txtCuidados = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Material:"));
        myPanel.add(txtMaterial);
        myPanel.add(Box.createHorizontalStrut(5)); // a spacer
        myPanel.add(new JLabel("Tipo de producto:"));
        myPanel.add(txtTipoP);
        myPanel.add(Box.createHorizontalStrut(5)); // a spacer
        myPanel.add(new JLabel("Dimensiones:"));
        myPanel.add(txtDimensiones);
        myPanel.add(Box.createHorizontalStrut(5)); // a spacer
        myPanel.add(new JLabel("Precio:"));
        myPanel.add(txtPrecio);
        myPanel.add(Box.createHorizontalStrut(5)); // a spacer
        myPanel.add(new JLabel("Nombre:"));
        myPanel.add(txtNombre);
        myPanel.add(Box.createHorizontalStrut(5)); // a spacer
        myPanel.add(new JLabel("Cuidados:"));
        myPanel.add(txtCuidados);

        int result = JOptionPane.showConfirmDialog(null, myPanel, 
                 "Ingrese los datos del nuevo Producto", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
           System.out.println("Matrial: " + txtMaterial.getText());
           System.out.println("Tipo de producto: " + txtTipoP.getText());
           System.out.println("Dimensiones: " + txtDimensiones.getText());
           System.out.println("Precio: " + txtPrecio.getText());
           System.out.println("Nombre: " + txtNombre.getText());
           System.out.println("Cuidados: " + txtCuidados.getText());
      }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        String n = (String)JOptionPane.showInputDialog("Ingrese id Producto:");
        System.out.println(n);
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        JTextField txtId = new JTextField(5);
        JTextField txtMaterial = new JTextField(5);
        JTextField txtTipoP = new JTextField(5);
        JTextField txtDimensiones = new JTextField(5);
        JTextField txtPrecio = new JTextField(5);
        JTextField txtNombre = new JTextField(5);
        JTextField txtCuidados = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("ID:"));
        myPanel.add(txtId);
        myPanel.add(Box.createHorizontalStrut(5)); // a spacer
        myPanel.add(new JLabel("Material:"));
        myPanel.add(txtMaterial);
        myPanel.add(Box.createHorizontalStrut(5)); // a spacer
        myPanel.add(new JLabel("Tipo de producto:"));
        myPanel.add(txtTipoP);
        myPanel.add(Box.createHorizontalStrut(5)); // a spacer
        myPanel.add(new JLabel("Dimensiones:"));
        myPanel.add(txtDimensiones);
        myPanel.add(Box.createHorizontalStrut(5)); // a spacer
        myPanel.add(new JLabel("Precio:"));
        myPanel.add(txtPrecio);
        myPanel.add(Box.createHorizontalStrut(5)); // a spacer
        myPanel.add(new JLabel("Nombre:"));
        myPanel.add(txtNombre);
        myPanel.add(Box.createHorizontalStrut(5)); // a spacer
        myPanel.add(new JLabel("Cuidados:"));
        myPanel.add(txtCuidados);

        int result = JOptionPane.showConfirmDialog(null, myPanel, 
                 "Ingrese los datos del nuevo Producto", JOptionPane.OK_CANCEL_OPTION);
        if (result == JOptionPane.OK_OPTION) {
           System.out.println("ID: " + txtId.getText());
           System.out.println("Material: " + txtMaterial.getText());
           System.out.println("Tipo de producto: " + txtTipoP.getText());
           System.out.println("Dimensiones: " + txtDimensiones.getText());
           System.out.println("Precio: " + txtPrecio.getText());
           System.out.println("Nombre: " + txtNombre.getText());
           System.out.println("Cuidados: " + txtCuidados.getText());
      }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String n = (String)JOptionPane.showInputDialog("Ingrese id del Producto a eliminar:");
        System.out.println(n);
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
