/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muebleria;

import java.util.ArrayList;

/**
 *
 * @author Josue
 */
public class Cliente extends javax.swing.JFrame {

    ArrayList<Producto> productos = new ArrayList();
    public Cliente() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbNompreP = new javax.swing.JComboBox<>();
        cbTipoP = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaCuidados = new javax.swing.JTextArea();
        btnAnadir = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        spCant = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaCarac = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(755, 483));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setText("Menú Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 50, 151, 30);

        cbNompreP.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        cbNompreP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbNompreP);
        cbNompreP.setBounds(57, 103, 138, 21);

        cbTipoP.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        cbTipoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbTipoP);
        cbTipoP.setBounds(231, 103, 138, 21);

        txtaCuidados.setEditable(false);
        txtaCuidados.setColumns(20);
        txtaCuidados.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtaCuidados.setRows(5);
        jScrollPane1.setViewportView(txtaCuidados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(96, 170, 206, 174);

        btnAnadir.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnadir);
        btnAnadir.setBounds(269, 401, 100, 27);

        btnComprar.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar);
        btnComprar.setBounds(379, 401, 110, 27);

        lblImagen.setText("Imagen");
        getContentPane().add(lblImagen);
        lblImagen.setBounds(493, 164, 220, 180);
        getContentPane().add(spCant);
        spCant.setBounds(397, 102, 46, 30);

        txtaCarac.setColumns(20);
        txtaCarac.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtaCarac.setRows(5);
        jScrollPane2.setViewportView(txtaCarac);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(480, 100, 230, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Furniture_pictograms.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-630, 30, 1380, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnComprar;
    private javax.swing.JComboBox<String> cbNompreP;
    private javax.swing.JComboBox<String> cbTipoP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JSpinner spCant;
    private javax.swing.JTextArea txtaCarac;
    private javax.swing.JTextArea txtaCuidados;
    // End of variables declaration//GEN-END:variables
}
