/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muebleria;

import java.awt.Image;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Josue
 */
public class Cliente extends javax.swing.JFrame {

    
    public Cliente() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblprecio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbNompreP = new javax.swing.JComboBox<>();
        cbTipoP = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaCuidados = new javax.swing.JTextArea();
        btnAnadir = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        spCant = new javax.swing.JSpinner();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaCarac = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(755, 483));
        getContentPane().setLayout(null);

        lblprecio.setText("\"\"");
        getContentPane().add(lblprecio);
        lblprecio.setBounds(160, 370, 41, 16);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setText("Menú Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(310, 50, 151, 29);

        cbNompreP.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        cbNompreP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNomprePActionPerformed(evt);
            }
        });
        getContentPane().add(cbNompreP);
        cbNompreP.setBounds(5, 103, 210, 25);

        cbTipoP.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        cbTipoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        cbTipoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoPActionPerformed(evt);
            }
        });
        getContentPane().add(cbTipoP);
        cbTipoP.setBounds(231, 103, 138, 25);

        txtaCuidados.setEditable(false);
        txtaCuidados.setColumns(20);
        txtaCuidados.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtaCuidados.setRows(5);
        jScrollPane1.setViewportView(txtaCuidados);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(96, 170, 203, 174);

        btnAnadir.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnAnadir.setText("Añadir");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnadir);
        btnAnadir.setBounds(269, 401, 100, 33);

        btnComprar.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar);
        btnComprar.setBounds(379, 401, 110, 33);

        lblImagen.setText("Imagen");
        getContentPane().add(lblImagen);
        lblImagen.setBounds(493, 164, 220, 180);

        spCant.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        getContentPane().add(spCant);
        spCant.setBounds(397, 102, 46, 30);

        txtaCarac.setColumns(20);
        txtaCarac.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtaCarac.setRows(5);
        jScrollPane2.setViewportView(txtaCarac);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(480, 100, 230, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Furniture_pictograms.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-630, 30, 1380, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
        // TODO add your handling code here:
        this.productos.add(new Producto(Integer.parseInt(cbNompreP.getSelectedItem().toString().split("-")[0]),cbNompreP.getSelectedItem().toString().split("-")[1],Double.parseDouble(lblprecio.getText()),(Integer)spCant.getValue()));
        
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        
        for(int i = 0; i < productos.size();i++){
            System.out.println(productos.get(i).toString());
        }
        Facturacion f = new Facturacion(this.usuario,this.productos);
        f.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnComprarActionPerformed

    private void cbNomprePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNomprePActionPerformed
        try {
            String[] eleccion = cbNompreP.getSelectedItem().toString().split("-");
            int id = Integer.parseInt(eleccion[0]);
            String execute = "EXECUTE SP_ConsultaEspecifica ?, 0";
            PreparedStatement sql = Conexion.getConexion().prepareStatement(execute);
            sql.setInt(1, id);
            ResultSet resultado = sql.executeQuery();
            resultado.next();
            txtaCuidados.setText("Cuidados: "+resultado.getString("cuidados"));
            txtaCarac.setText("Color: "+resultado.getString("Color")
            +"\n Dimensiones: "+resultado.getString("altura")+"x"+resultado.getString("longitud")+"x"+resultado.getString("profundidad")+"\nTipo Material: "+resultado.getString("tipoMaterial"));
            lblImagen.setIcon( new ImageIcon(new ImageIcon(resultado.getBytes("imagen")).getImage().getScaledInstance(256, 256, Image.SCALE_DEFAULT)));
            lblprecio.setText(resultado.getDouble("precio")+"");
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cbNomprePActionPerformed

    private void cbTipoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoPActionPerformed
        try {
            // TODO add your handling code here:
            if(cbTipoP.getSelectedItem().toString().equals("Todos")){
                String select = "SELECT COUNT(idProducto) FROM Producto";
                PreparedStatement sql = Conexion.getConexion().prepareStatement(select);
            
                ResultSet resultado = sql.executeQuery();
                resultado.next();
                int cantidad = resultado.getInt(1);
                String[] opciones = new String[cantidad];
                cantidad = 0;
                
                select = "SELECT idProducto,Nombre FROM Producto";
                sql = Conexion.getConexion().prepareStatement(select);
                resultado = sql.executeQuery();
                
                while(resultado.next()){
                    opciones[cantidad] = resultado.getString("IdProducto")+"-"+resultado.getString("Nombre");
                    cantidad++;
                }
                cbNompreP.setModel(new javax.swing.DefaultComboBoxModel<>(opciones));
            }else{
                String select = "SELECT COUNT(idProducto) FROM Producto p INNER JOIN TipoProducto tp ON p.idTipoProducto = tp.idTipoProducto WHERE tp.tipoproducto = ?";
                PreparedStatement sql = Conexion.getConexion().prepareStatement(select);
                sql.setString(1, cbTipoP.getSelectedItem().toString());
                
                ResultSet resultado = sql.executeQuery();
                resultado.next();
                int cantidad = resultado.getInt(1);
                String[] opciones = new String[cantidad];
                cantidad = 0;
                
                select = "SELECT idProducto,Nombre FROM Producto p INNER JOIN TipoProducto tp ON p.idTipoProducto = tp.idTipoProducto WHERE tp.tipoproducto = ?";
                sql = Conexion.getConexion().prepareStatement(select);
                sql.setString(1, cbTipoP.getSelectedItem().toString());
                resultado = sql.executeQuery();
                
                while(resultado.next()){
                    opciones[cantidad] = resultado.getString("IdProducto")+"-"+resultado.getString("Nombre");
                    cantidad++;
                }
                cbNompreP.setModel(new javax.swing.DefaultComboBoxModel<>(opciones));
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_cbTipoPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnadir;
    private javax.swing.JButton btnComprar;
    private javax.swing.JComboBox<String> cbNompreP;
    private javax.swing.JComboBox<String> cbTipoP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblprecio;
    private javax.swing.JSpinner spCant;
    private javax.swing.JTextArea txtaCarac;
    private javax.swing.JTextArea txtaCuidados;
    // End of variables declaration//GEN-END:variables
    public Usuario usuario;
    ArrayList<Producto> productos;

    public Cliente(Usuario usuario) {
        try {
            this.usuario = usuario;
            this.productos  = new ArrayList();
            initComponents();
            String select = "SELECT COUNT(tipoProducto) FROM TipoProducto";
            
            
            PreparedStatement sql = Conexion.getConexion().prepareStatement(select);
            
            
            ResultSet resultado = sql.executeQuery();
            resultado.next();
            int cantidad = resultado.getInt(1)+1;
            
            String[] opciones = new String[cantidad];
            
            
            
            select = "SELECT tipoProducto FROM TipoProducto";
            sql = Conexion.getConexion().prepareStatement(select);
            resultado = sql.executeQuery();
            opciones[0] = "Todos";
            cantidad = 1;
            while(resultado.next()){
                opciones[cantidad] = resultado.getString("tipoProducto");
                cantidad++;
            }
            
            cbTipoP.setModel(new javax.swing.DefaultComboBoxModel<>(opciones));
            
            
            select = "SELECT COUNT(idProducto) FROM Producto";
            sql = Conexion.getConexion().prepareStatement(select);

            resultado = sql.executeQuery();
            resultado.next();
            cantidad = resultado.getInt(1);
            opciones = new String[cantidad];
            cantidad = 0;

            select = "SELECT idProducto,Nombre FROM Producto";
            sql = Conexion.getConexion().prepareStatement(select);
            resultado = sql.executeQuery();

            while(resultado.next()){
                opciones[cantidad] = resultado.getString("IdProducto")+"-"+resultado.getString("Nombre");
                cantidad++;
            }
            cbNompreP.setModel(new javax.swing.DefaultComboBoxModel<>(opciones));

            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
}
