/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muebleria;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Josue
 */
public class Facturacion extends javax.swing.JFrame {

    /**
     * Creates new form Facturacion
     */
    public Facturacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPrecio = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCant = new javax.swing.JTextArea();
        cbTPago = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(740, 540));
        getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel5.setText("Nombre:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 120, 70, 30);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        jLabel4.setText("Tipo de pago:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 80, 70, 20);

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel6.setText("Cantidad:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 120, 70, 30);

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel7.setText("Precio:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 120, 70, 30);

        txtPrecio.setEditable(false);
        txtPrecio.setColumns(10);
        txtPrecio.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        txtPrecio.setRows(5);
        jScrollPane3.setViewportView(txtPrecio);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(460, 150, 130, 230);

        txtCant.setEditable(false);
        txtCant.setColumns(5);
        txtCant.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        txtCant.setRows(5);
        jScrollPane2.setViewportView(txtCant);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(360, 150, 80, 230);

        cbTPago.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        cbTPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta", "Paypal", "Sinpe Móvil" }));
        cbTPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTPagoActionPerformed(evt);
            }
        });
        getContentPane().add(cbTPago);
        cbTPago.setBounds(350, 80, 140, 30);

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setText("Facturación");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(306, 33, 137, 30);

        btnComprar.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        btnComprar.setText("Terminar compra");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar);
        btnComprar.setBounds(290, 440, 143, 27);

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        jLabel2.setText("Total:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 390, 34, 22);

        lblTotal.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        lblTotal.setText("0");
        getContentPane().add(lblTotal);
        lblTotal.setBounds(460, 390, 130, 18);

        txtArea.setEditable(false);
        txtArea.setColumns(15);
        txtArea.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 150, 190, 230);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-vector.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 740, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        try {
            // TODO add your handling code here:
            String execute = "EXECUTE SP_CrearFactura ?, ?, ?, 0";
            PreparedStatement sql = Conexion.getConexion().prepareStatement(execute);
            sql.setInt(1,cbTPago.getSelectedIndex()+1);
            sql.setInt(2,usuario.id);
            switch(cbTPago.getSelectedIndex()) {
                case 0:
                    sql.setInt(3,0);
                  break;
                case 1:
                    sql.setInt(3,5);
                  break;
                default:
                    sql.setInt(3,13);
              }
            
            ResultSet res = sql.executeQuery();
            
            res.next();
            
            int idFactura = res.getInt(1);
            
            execute = "EXECUTE SP_Facturacion ?, ?, ?, 0";
            
            for(int i  = 0; i < productos.size(); i++){
                sql = Conexion.getConexion().prepareStatement(execute);
                sql.setInt(1, productos.get(i).idProducto);
                sql.setInt(2, idFactura);
                sql.setInt(3, productos.get(i).cantidad);
                
                sql.executeUpdate();
            }
            
            
            Index i = new Index();
            i.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Facturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    private void cbTPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JComboBox<String> cbTPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextArea txtCant;
    private javax.swing.JTextArea txtPrecio;
    // End of variables declaration//GEN-END:variables
    public Usuario usuario;
    ArrayList<Producto> productos;

    public Facturacion(Usuario usuario, ArrayList<Producto> productos) {
        this.usuario = usuario;
        this.productos = productos;
        initComponents();
        String nombres = "";
        String cantidades = "";
        String precios = "";
        double precioFinal = 0;
        for(int i = 0; i < productos.size();i++){
           nombres += productos.get(i).nombre + "\n";
           cantidades +=  productos.get(i).cantidad + "\n";
           precios += productos.get(i).precio + "\n";
           precioFinal += productos.get(i).precio*productos.get(i).cantidad;
        }
        txtArea.setText(nombres);
        txtCant.setText(cantidades);
        txtPrecio.setText(precios);
        lblTotal.setText(""+precioFinal);
    }
    
}
